# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 400)
        MainWindow.setMinimumSize(QtCore.QSize(300, 400))
        MainWindow.setMaximumSize(QtCore.QSize(300, 400))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(180, 370, 113, 32))
        self.pushButton.setObjectName("pushButton")
        self.student_name = QtWidgets.QLabel(parent=self.centralwidget)
        self.student_name.setGeometry(QtCore.QRect(10, 10, 101, 16))
        self.student_name.setObjectName("student_name")
        self.attempts = QtWidgets.QLabel(parent=self.centralwidget)
        self.attempts.setGeometry(QtCore.QRect(10, 50, 101, 16))
        self.attempts.setObjectName("attempts")
        self.Score_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.Score_2.setGeometry(QtCore.QRect(160, 90, 60, 16))
        self.Score_2.setObjectName("Score_2")
        self.Score_1 = QtWidgets.QLabel(parent=self.centralwidget)
        self.Score_1.setGeometry(QtCore.QRect(10, 90, 60, 16))
        self.Score_1.setObjectName("Score_1")
        self.Score_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.Score_3.setGeometry(QtCore.QRect(10, 150, 60, 16))
        self.Score_3.setObjectName("Score_3")
        self.input_name = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.input_name.setGeometry(QtCore.QRect(130, 10, 113, 21))
        self.input_name.setObjectName("input_name")
        self.input_attempt = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.input_attempt.setGeometry(QtCore.QRect(130, 50, 113, 21))
        self.input_attempt.setObjectName("input_attempt")
        self.Score1_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Score1_input.setGeometry(QtCore.QRect(10, 110, 113, 21))
        self.Score1_input.setObjectName("Score1_input")
        self.Score2_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Score2_input.setGeometry(QtCore.QRect(160, 110, 113, 21))
        self.Score2_input.setObjectName("Score2_input")
        self.Score3_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Score3_input.setGeometry(QtCore.QRect(10, 170, 113, 21))
        self.Score3_input.setObjectName("Score3_input")
        self.Score4_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Score4_input.setGeometry(QtCore.QRect(160, 170, 113, 21))
        self.Score4_input.setObjectName("Score4_input")
        self.Enter_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Enter_button.setGeometry(QtCore.QRect(90, 210, 131, 51))
        self.Enter_button.setObjectName("Enter_button")
        self.Score_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.Score_4.setGeometry(QtCore.QRect(160, 150, 60, 16))
        self.Score_4.setObjectName("Score_4")
        self.submit_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.submit_button.setGeometry(QtCore.QRect(90, 210, 131, 51))
        self.submit_button.setObjectName("submit_button")
        self.Message = QtWidgets.QLabel(parent=self.centralwidget)
        self.Message.setGeometry(QtCore.QRect(50, 270, 201, 31))
        self.Message.setStyleSheet("color: rgb(252, 1, 7);")
        self.Message.setText("")
        self.Message.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Message.setObjectName("Message")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 300, 33))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Grades"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.student_name.setText(_translate("MainWindow", "Student_name:"))
        self.attempts.setText(_translate("MainWindow", "No of attempts:"))
        self.Score_2.setText(_translate("MainWindow", "Score 2:"))
        self.Score_1.setText(_translate("MainWindow", "Score 1:"))
        self.Score_3.setText(_translate("MainWindow", "Score 3:"))
        self.Enter_button.setText(_translate("MainWindow", "Enter"))
        self.Score_4.setText(_translate("MainWindow", "Score 4:"))
        self.submit_button.setText(_translate("MainWindow", "Submit buttons"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
